# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Static Site

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # first checkout the source
    - uses: actions/checkout@v3
    - name: Build and push
      uses: actions/setup-node@v3
      with:
        node-version: 10.x
        cache: 'npm'
    - run: npm ci
    - run: npx docpad generate --env static --out out/
    - run: | 
        if grep -q '<%=' "out/index.html"; then
        echo 'Error: template code detected in output, aborting!'
        exit 1;
        fi

