
name: Update Static Site

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # first checkout the source
    - uses: actions/checkout@v6
    - name: Build and push
      uses: actions/setup-node@v6
      with:
        node-version: lts/*
    - run: npm ci
    # then checkout the destination
    - uses: actions/checkout@v6
      with:
        ref: 'gh-pages'
        path: '_site/'
    # build & test the site
    - run: npm run build
    - run: npm test
    # push it to gh-pages if there are changes (dependency bumps generally don't change the built site)
    - run: ./.github/workflows/push-if-changes.sh
        
