# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Static Site

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # first checkout the source
    - uses: actions/checkout@v3
    - name: Build and push
      uses: actions/setup-node@v3
      with:
        node-version: 10.x
        cache: 'npm'
    - run: npm ci
    # then checkout the destination
    - uses: actions/checkout@v3
      with:
        ref: 'gh-pages'
        path: 'out/'
    - run: npx docpad generate --env static --out out/
    - run: | 
        pushd out/
        if grep -q '<%=' "index.html"; then
        echo 'Error: template code detected in output, aborting!'
        exit 1;
        fi
        git config --global user.email "actions_bot@github.com"
        git config --global user.name "GH Actions Bot"
        git add -f -A .
        git commit -m "Updating gh-pages"
        git push origin gh-pages
