
name: Update Static Site

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # first checkout the source
    - uses: actions/checkout@v6
    - name: Build and push
      uses: actions/setup-node@v6
      with:
        node-version: lts/*
    - run: npm ci
    # then checkout the destination
    - uses: actions/checkout@v6
      with:
        ref: 'gh-pages'
        path: '_site/'
    # build the site
    - run: npm run build
    # push it to gh-pages
    - run: | 
        pushd _site/
        if grep -q '<%=' "index.html"; then
        echo 'Error: template code detected in output, aborting!'
        exit 1;
        fi
        # Only commit and push if there are changes
        if ! git diff-index --quiet HEAD --; then
          git config --global user.email "actions_bot@github.com"
          git config --global user.name "GH Actions Bot"
          git add -f -A .
          git commit -m "Updating gh-pages: ${{ github.event.head_commit.message }}"
          git push origin gh-pages
        else
          echo "No changes to deploy"
        fi